services:
  - type: web
    name: archess-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 24
      - key: PORT
        fromService:
          type: web
          name: archess-backend
          property: port
      - key: DB_PATH
        sync: false
      - key: CLIENT_ORIGIN
        sync: false

  - type: static
    name: archess-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
